apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.application }}
  labels:
    app: {{ .Values.application }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ .Values.application }}
        spec:
          restartPolicy: OnFailure
          containers:
            - name: {{ .Values.application }}
              image: {{ .Values.cronjob.image.repository }}:{{ .Values.cronjob.image.tag }}
              resources:
                {{- toYaml .Values.cronjob.resources | nindent 16 }}
              env:
              {{- range .Values.cronjob.env }}
                - name: {{ .name }}
                  value: "{{ .value }}"
              {{- end }}
