apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 3.2.5
    chart: k8s-monitoring
    helm:
      releaseName: k8s-monitoring
      valuesObject:
        cluster:
          name: devops-engineer-assignment
        destinations:
          - name: Loki
            type: loki
            url: http://grafana-loki.observability.svc.cluster.local:3100
        podLogs:
          enabled: true
        clusterEvents:
          enabled: true
        alloy-logs:
          enabled: true
        alloy-singleton:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
