apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 76.3.0
    chart: kube-prometheus-stack
    helm:
      releaseName: kube-prometheus-stack
      valuesObject:
        alertmanager:
          enabled: false
        kubeApiServer:
          enabled: false
        kubeEtcd:
          enabled: false
        kubeControllerManager:
          enabled: false
        kubeScheduler:
          enabled: false
        grafana:
          ingress:
            enabled: true
            path: /
            hosts:
              - grafana.dmytrorybak.click
            annotations: {}
          sidecar:
            datasources:
              alertmanager:
                enabled: false
          additionalDataSources:
            - name: Loki
              type: loki
              url: http://loki.observability.svc.cluster.local:3100
              access: proxy
            - name: Tempo
              type: tempo
              url: http://tempo.observability.svc.cluster.local:3200
              access: proxy
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
